# Generated by Django 5.2.6 on 2025-10-01 04:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('agent', 'Agent'), ('supervisor', 'Supervisor'), ('manager', 'Manager')], default='agent', max_length=20)),
                ('county', models.CharField(choices=[('nairobi', 'Nairobi'), ('mombasa', 'Mombasa'), ('kwale', 'Kwale'), ('kilifi', 'Kilifi'), ('tana_river', 'Tana River'), ('lamu', 'Lamu'), ('taita_taveta', 'Taita Taveta'), ('garissa', 'Garissa'), ('wajir', 'Wajir'), ('mandera', 'Mandera'), ('marsabit', 'Marsabit'), ('isiolo', 'Isiolo'), ('meru', 'Meru'), ('tharaka_nithi', 'Tharaka-Nithi'), ('embu', 'Embu'), ('kitui', 'Kitui'), ('machakos', 'Machakos'), ('makueni', 'Makueni'), ('nyandarua', 'Nyandarua'), ('nyeri', 'Nyeri'), ('kirinyaga', 'Kirinyaga'), ('muranga', "Murang'a"), ('kiambu', 'Kiambu'), ('turkana', 'Turkana'), ('west_pokot', 'West Pokot'), ('samburu', 'Samburu'), ('trans_nzoia', 'Trans Nzoia'), ('uasin_gishu', 'Uasin Gishu'), ('elgeyo_marakwet', 'Elgeyo-Marakwet'), ('nandi', 'Nandi'), ('baringo', 'Baringo'), ('laikipia', 'Laikipia'), ('nakuru', 'Nakuru'), ('narok', 'Narok'), ('kajiado', 'Kajiado'), ('kericho', 'Kericho'), ('bomet', 'Bomet'), ('kakamega', 'Kakamega'), ('vihiga', 'Vihiga'), ('bungoma', 'Bungoma'), ('busia', 'Busia'), ('siaya', 'Siaya'), ('kisumu', 'Kisumu'), ('homa_bay', 'Homa Bay'), ('migori', 'Migori'), ('kisii', 'Kisii'), ('nyamira', 'Nyamira')], max_length=50)),
                ('sublocation', models.CharField(choices=[('central', 'Central'), ('east', 'East'), ('west', 'West'), ('north', 'North'), ('south', 'South'), ('urban', 'Urban'), ('rural', 'Rural')], max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('employee_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('county', models.CharField(choices=[('nairobi', 'Nairobi'), ('mombasa', 'Mombasa'), ('kwale', 'Kwale'), ('kilifi', 'Kilifi'), ('tana_river', 'Tana River'), ('lamu', 'Lamu'), ('taita_taveta', 'Taita Taveta'), ('garissa', 'Garissa'), ('wajir', 'Wajir'), ('mandera', 'Mandera'), ('marsabit', 'Marsabit'), ('isiolo', 'Isiolo'), ('meru', 'Meru'), ('tharaka_nithi', 'Tharaka-Nithi'), ('embu', 'Embu'), ('kitui', 'Kitui'), ('machakos', 'Machakos'), ('makueni', 'Makueni'), ('nyandarua', 'Nyandarua'), ('nyeri', 'Nyeri'), ('kirinyaga', 'Kirinyaga'), ('muranga', "Murang'a"), ('kiambu', 'Kiambu'), ('turkana', 'Turkana'), ('west_pokot', 'West Pokot'), ('samburu', 'Samburu'), ('trans_nzoia', 'Trans Nzoia'), ('uasin_gishu', 'Uasin Gishu'), ('elgeyo_marakwet', 'Elgeyo-Marakwet'), ('nandi', 'Nandi'), ('baringo', 'Baringo'), ('laikipia', 'Laikipia'), ('nakuru', 'Nakuru'), ('narok', 'Narok'), ('kajiado', 'Kajiado'), ('kericho', 'Kericho'), ('bomet', 'Bomet'), ('kakamega', 'Kakamega'), ('vihiga', 'Vihiga'), ('bungoma', 'Bungoma'), ('busia', 'Busia'), ('siaya', 'Siaya'), ('kisumu', 'Kisumu'), ('homa_bay', 'Homa Bay'), ('migori', 'Migori'), ('kisii', 'Kisii'), ('nyamira', 'Nyamira')], max_length=50)),
                ('sublocation', models.CharField(choices=[('central', 'Central'), ('east', 'East'), ('west', 'West'), ('north', 'North'), ('south', 'South'), ('urban', 'Urban'), ('rural', 'Rural')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_entries', models.IntegerField(default=0)),
                ('active_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('manager_feedback', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('service_type', models.CharField(choices=[('installation', 'Installation'), ('maintenance', 'Maintenance'), ('repair', 'Repair'), ('upgrade', 'Upgrade'), ('consultation', 'Consultation')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=20)),
                ('agent_feedback', models.TextField(blank=True)),
                ('supervisor_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_rows', to='api.report')),
            ],
            options={
                'unique_together': {('report', 'entry_number')},
            },
        ),
    ]
